### ISSUE TITLE
WanionLib-1.12.2-1.6.jar Update Causes Crashes with UniDict-1.12.2-2.9.1.jar

### ISSUE THREAD

**Issue by raziel23x** [WanionCane/WanionLib#7]
[crash-2018-10-28_00.25.39-client.txt](https://github.com/WanionCane/WanionLib/files/2522460/crash-2018-10-28_00.25.39-client.txt)
Here is the Crash log when i revert to previous update UniDict no longer crashes

**Comment by kellixon** [comment]
Same problem, previous version stable

**Comment by SirAron111** [comment]
Same problem, same Crash

**Comment by WanionCane** [comment]
omg.. I don't know how a super important class got deleted.. I will remove the 1.12.2-1.6 version of Wanionlib, and, prease rollback to the 1.12.2-1.5 version of WanionLib

**Comment by kellixon** [comment]
How? How does the author test his mod?

**Comment by WanionCane** [comment]
@kellixon I don't remember changing anything on WanionLib that would compromise the behavior of UniDict, but somehow one very important class got deleted, and I have zero clue about how that happend, so... a fix will soon be avaiable on Curse.
and, I did test the mod, but, the changes that were made on that version were related to my another mod, Bigger Crafting Tables, that's why I felt that it didn't had need to test UniDict.

**Comment by WanionCane** [comment]
[WanionLib-1.12.2-1.7.jar](https://minecraft.curseforge.com/projects/wanionlib/files/2632700)
